backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "images"

collections:
  - name: "contenido"
    label: "Contenido de la Web"
    files:
      - file: "datos.json"
        label: "Textos y Configuración"
        name: "textos"
        fields:
          - { label: "Título Principal", name: "textos.hero_titulo", widget: "string" }
          - { label: "Subtítulo Principal", name: "textos.hero_subtitulo", widget: "text" }
          - { label: "Título Nosotros", name: "textos.nosotros_titulo", widget: "string" }
          - { label: "Descripción 1 Nosotros", name: "textos.nosotros_descripcion_1", widget: "text" }
          - { label: "Descripción 2 Nosotros", name: "textos.nosotros_descripcion_2", widget: "text" }